<template><main class="security-page"><header><span class="tag">账号安全</span><h1>登录设备与账号治理</h1><p>管理当前会话、登录凭据、手机号和账号注销。</p></header><section class="card"><div class="section-title"><div><h2>登录设备</h2><p>发现陌生设备时立即撤销。</p></div><button class="btn btn-sm" @click="loadSessions">刷新</button></div><div v-if="sessions.length" class="sessions"><article v-for="item in sessions" :key="item.id"><div><strong>{{item.device_name||'未知设备'}}</strong><p>{{item.current?'当前设备':'其他设备'}} · {{item.last_seen_at||'最近活跃时间未知'}}</p></div><span v-if="item.revoked" class="tag gray">已撤销</span><button v-else-if="!item.current" class="btn btn-danger btn-sm" data-action="revoke-session" @click="revoke(item)">撤销</button><span v-else class="tag green">当前</span></article></div><p v-else class="empty">暂无会话记录</p></section><section class="card"><h2>修改密码</h2><p>建议为教师、科研人员和管理员账号设置独立强密码。</p><RouterLink class="btn" to="/account/password">设置或重置密码</RouterLink></section><section class="card"><h2>更换手机号</h2><p>需分别验证当前手机号和新手机号，成功后所有设备都会退出。</p><button class="btn" @click="phoneOpen=!phoneOpen">{{phoneOpen?'收起':'开始换绑'}}</button><div v-if="phoneOpen" class="notice">请依次获取旧号码与新号码验证码，再提交换绑。该流程不会迁移其他账号数据。</div></section><section class="card danger"><h2>注销账号</h2><p>申请后进入 7 天冷静期并立即退出普通业务。到期后身份数据会删除或匿名化。</p><button class="btn btn-danger" @click="requestDeletion">申请注销</button><p v-if="message" class="message">{{message}}</p></section></main></template>
<script setup>
import { onMounted, ref } from 'vue';import { securityApi } from '@/api/auth'
const props=defineProps({initialSessions:{type:Array,default:()=>[]}});const sessions=ref([...props.initialSessions]),phoneOpen=ref(false),message=ref('')
async function loadSessions(){try{sessions.value=await securityApi.sessions()}catch{message.value='会话列表加载失败'}}
async function revoke(item){await securityApi.revokeSession(item.id);item.revoked=true}
async function requestDeletion(){if(!window.confirm('确认申请注销？将立即退出并进入 7 天冷静期。'))return;try{const data=await securityApi.requestDeletion();message.value=`注销冷静期至 ${data.execute_after}`}catch(e){message.value=e?.message||'申请失败'}}
onMounted(()=>{if(!sessions.value.length)loadSessions()})
</script>
<style scoped>.security-page{max-width:920px;margin:0 auto;padding:42px 24px 70px}.security-page header>p,.card>p{color:var(--ink2)}h1{margin:12px 0 4px}.card{background:white;border:1px solid var(--line);border-radius:18px;padding:24px;margin-top:18px;box-shadow:var(--shadow-sm)}.section-title,.sessions article{display:flex;justify-content:space-between;align-items:center;gap:16px}.sessions{margin-top:14px}.sessions article{padding:14px 0;border-top:1px solid var(--line2)}.sessions p{font-size:12px;color:var(--ink3)}.empty{padding:18px 0}.notice,.message{margin-top:12px;padding:12px;border-radius:10px;background:var(--warn-bg);color:var(--warn-deep)}.danger{border-color:var(--err-border)}</style>
