/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/research/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Run */
        post: operations["create_run_api_research_v1_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/research/v1/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Run Events */
        get: operations["stream_run_events_api_research_v1_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness */
        get: operations["liveness_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness */
        get: operations["readiness_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActorType
         * @enum {string}
         */
        ActorType: "human" | "agent" | "service" | "tool";
        /**
         * AdapterType
         * @enum {string}
         */
        AdapterType: "native" | "mcp" | "http" | "sandbox";
        /**
         * AgentContext
         * @description Transient execution context handed to agent modules (not persisted).
         */
        AgentContext: {
            /**
             * Active Document Id
             * @default null
             */
            active_document_id: string | null;
            /** Evidence Bundle Ids */
            evidence_bundle_ids?: string[];
            /** Locale */
            locale: string;
            /** Memory Ids */
            memory_ids?: string[];
            /** Permissions */
            permissions?: string[];
            /** Project Id */
            project_id: string;
            /** Reasoning Policy Id */
            reasoning_policy_id: string;
            /** Run Id */
            run_id: string;
            /**
             * Selection
             * @default null
             */
            selection: {
                [key: string]: unknown;
            } | null;
            /** Tenant Id */
            tenant_id: string;
            /** Timezone */
            timezone: string;
            /** User Id */
            user_id: string;
        };
        /**
         * ApprovalRequest
         * @description M0 addition over 02 §5.10: ``tenant_id``/``project_id`` explicit.
         */
        ApprovalRequest: {
            /** Action */
            action: string;
            /** Arguments Redacted */
            arguments_redacted?: {
                [key: string]: unknown;
            };
            /** Data Scope */
            data_scope?: string[];
            /**
             * Estimated Cost Minor Units
             * @default null
             */
            estimated_cost_minor_units: number | null;
            /**
             * Expires At
             * @default null
             */
            expires_at: string | null;
            /** Id */
            id: string;
            /** Project Id */
            project_id: string;
            /** Reason */
            reason: string;
            /**
             * Requested At
             * Format: date-time
             */
            requested_at: string;
            /**
             * Resolution Note
             * @default null
             */
            resolution_note: string | null;
            /**
             * Resolved At
             * @default null
             */
            resolved_at: string | null;
            /**
             * Resolved By
             * @default null
             */
            resolved_by: string | null;
            risk_tier: components["schemas"]["RiskTier"];
            /** Run Id */
            run_id: string;
            status: components["schemas"]["ApprovalStatus"];
            /** Tenant Id */
            tenant_id: string;
            /**
             * Tool Call Id
             * @default null
             */
            tool_call_id: string | null;
        };
        /**
         * ApprovalStatus
         * @enum {string}
         */
        ApprovalStatus: "pending" | "approved" | "rejected" | "expired" | "cancelled";
        /** Artifact */
        Artifact: {
            artifact_type: components["schemas"]["ArtifactType"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Created By Activity Id */
            created_by_activity_id: string;
            /** Id */
            id: string;
            /** Media Type */
            media_type: string;
            /** Project Id */
            project_id: string;
            retention_policy: components["schemas"]["RetentionPolicy"];
            rights_status: components["schemas"]["RightsStatus"];
            /** Sha256 */
            sha256: string;
            /** Size Bytes */
            size_bytes: number;
            /** Source Artifact Ids */
            source_artifact_ids?: string[];
            /** Storage Uri */
            storage_uri: string;
            /** Tenant Id */
            tenant_id: string;
        };
        /**
         * ArtifactType
         * @enum {string}
         */
        ArtifactType: "source_pdf" | "parsed_document" | "translation" | "latex_source" | "compiled_pdf" | "notebook" | "dataset" | "figure" | "review_report" | "proof" | "reproducibility_package";
        /**
         * BlockType
         * @enum {string}
         */
        BlockType: "heading" | "paragraph" | "display_math" | "inline_math" | "figure" | "table" | "caption" | "citation" | "footnote" | "code";
        /** Budget */
        Budget: {
            /** Currency */
            currency: string;
            /** Max Cost Minor Units */
            max_cost_minor_units: number;
            /** Max Parallel Tasks */
            max_parallel_tasks: number;
            /** Max Runtime Seconds */
            max_runtime_seconds: number;
            /** Max Sources */
            max_sources: number;
        };
        /**
         * CitationRecord
         * @description M0 addition over 02 §5.8: ``tenant_id``/``project_id`` explicit.
         */
        CitationRecord: {
            /** Citation Key */
            citation_key: string;
            /** Cited Claim Ids */
            cited_claim_ids?: string[];
            /** Id */
            id: string;
            /** Item Id */
            item_id: string;
            /** Project Id */
            project_id: string;
            /**
             * Target Version
             * @default null
             */
            target_version: string | null;
            /** Tenant Id */
            tenant_id: string;
            /**
             * Verified At
             * Format: date-time
             */
            verified_at: string;
            verified_source: components["schemas"]["CitationVerifiedSource"];
            version_status: components["schemas"]["CitationVersionStatus"];
        };
        /**
         * CitationVerifiedSource
         * @enum {string}
         */
        CitationVerifiedSource: "crossref" | "datacite" | "openalex" | "pubmed" | "arxiv";
        /**
         * CitationVersionStatus
         * @enum {string}
         */
        CitationVersionStatus: "current" | "updated" | "retracted" | "expression_of_concern" | "unknown";
        /**
         * ClaimKind
         * @enum {string}
         */
        ClaimKind: "factual" | "mathematical" | "methodological" | "interpretive" | "hypothesis";
        /** ClaimRecord */
        ClaimRecord: {
            claim_kind: components["schemas"]["ClaimKind"];
            /** Claim Text */
            claim_text: string;
            /** @default null */
            confidence_band: components["schemas"]["ConfidenceBand"] | null;
            /** Created By Activity Id */
            created_by_activity_id: string;
            /**
             * Document Id
             * @default null
             */
            document_id: string | null;
            /** Evidence Links */
            evidence_links?: components["schemas"]["EvidenceLink"][];
            /** Id */
            id: string;
            /**
             * Last Verified At
             * @default null
             */
            last_verified_at: string | null;
            /** Project Id */
            project_id: string;
            support_status: components["schemas"]["SupportStatus"];
            /** Tenant Id */
            tenant_id: string;
            /**
             * Version
             * @default 0
             */
            version: number;
        };
        /**
         * ConfidenceBand
         * @enum {string}
         */
        ConfidenceBand: "low" | "medium" | "high";
        /**
         * CreateRunRequest
         * @description Request body of ``POST /api/research/v1/runs`` (M0 addition).
         */
        CreateRunRequest: {
            budget?: components["schemas"]["Budget"] | null;
            /** Input Artifact Ids */
            input_artifact_ids?: string[];
            /** @default standard */
            reasoning_policy_id: components["schemas"]["ReasoningPolicyId"];
            run_type: components["schemas"]["RunType"];
        };
        /** DocumentBlock */
        DocumentBlock: {
            /**
             * Bbox
             * @default null
             */
            bbox: [
                number,
                number,
                number,
                number
            ] | null;
            /** Block Id */
            block_id: string;
            /** Content Hash */
            content_hash: string;
            /**
             * Label
             * @default null
             */
            label: string | null;
            /**
             * Latex
             * @default null
             */
            latex: string | null;
            /**
             * Page Index
             * @default null
             */
            page_index: number | null;
            /** References */
            references?: string[];
            /**
             * Text
             * @default null
             */
            text: string | null;
            type: components["schemas"]["BlockType"];
        };
        /**
         * DocumentIR
         * @description M0 addition over 02 §5.9: ``tenant_id``/``project_id`` explicit.
         */
        DocumentIR: {
            /** Blocks */
            blocks?: components["schemas"]["DocumentBlock"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Document Id */
            document_id: string;
            /** Parser Name */
            parser_name: string;
            /** Parser Version */
            parser_version: string;
            /** Project Id */
            project_id: string;
            /** Source Artifact Id */
            source_artifact_id: string;
            /** Tenant Id */
            tenant_id: string;
        };
        /**
         * EntailmentStatus
         * @enum {string}
         */
        EntailmentStatus: "entailed" | "partial" | "not_entailed" | "not_checked";
        /** EvidenceLink */
        EvidenceLink: {
            entailment_status: components["schemas"]["EntailmentStatus"];
            /** Evidence Id */
            evidence_id: string;
            relation: components["schemas"]["EvidenceRelation"];
        };
        /**
         * EvidenceRecord
         * @description Verbatim, hash-anchored citation target: the evidence-native core.
         */
        EvidenceRecord: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: string;
            locator?: components["schemas"]["Locator"];
            /** Parser Name */
            parser_name: string;
            /** Parser Version */
            parser_version: string;
            /** Project Id */
            project_id: string;
            /** Quoted Text */
            quoted_text: string;
            /** Quoted Text Sha256 */
            quoted_text_sha256: string;
            rights_status: components["schemas"]["RightsStatus"];
            /** Source Artifact Id */
            source_artifact_id: string;
            source_identifier: components["schemas"]["SourceIdentifier"];
            /** Tenant Id */
            tenant_id: string;
        };
        /**
         * EvidenceRelation
         * @enum {string}
         */
        EvidenceRelation: "supports" | "contradicts" | "contextualizes";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * IdempotencyKind
         * @enum {string}
         */
        IdempotencyKind: "idempotent" | "keyed" | "non_idempotent";
        /** Locator */
        Locator: {
            /**
             * Bbox
             * @default null
             */
            bbox: [
                number,
                number,
                number,
                number
            ] | null;
            /**
             * Char End
             * @default null
             */
            char_end: number | null;
            /**
             * Char Start
             * @default null
             */
            char_start: number | null;
            /**
             * Page Index
             * @default null
             */
            page_index: number | null;
            /** Section Path */
            section_path?: string[];
        };
        /**
         * MemoryRecord
         * @description M0 addition over 02 §5.12: ``tenant_id`` explicit.
         */
        MemoryRecord: {
            /** Content */
            content: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Expires At
             * @default null
             */
            expires_at: string | null;
            /** Id */
            id: string;
            memory_type: components["schemas"]["MemoryType"];
            scope: components["schemas"]["MemoryScope"];
            sensitivity: components["schemas"]["Sensitivity"];
            /** Source Ids */
            source_ids?: string[];
            /** Subject Id */
            subject_id: string;
            /**
             * Supersedes Id
             * @default null
             */
            supersedes_id: string | null;
            /** Tenant Id */
            tenant_id: string;
            verification_status: components["schemas"]["MemoryVerificationStatus"];
        };
        /**
         * MemoryScope
         * @enum {string}
         */
        MemoryScope: "run" | "project" | "user_preference";
        /**
         * MemoryType
         * @enum {string}
         */
        MemoryType: "decision" | "constraint" | "preference" | "verified_fact" | "working_note";
        /**
         * MemoryVerificationStatus
         * @enum {string}
         */
        MemoryVerificationStatus: "verified" | "user_asserted" | "derived" | "unverified";
        /**
         * NetworkPolicy
         * @enum {string}
         */
        NetworkPolicy: "none" | "allowlist" | "open_with_review";
        /** ReasoningPolicy */
        ReasoningPolicy: {
            /** Allow Hypothesis Tournament */
            allow_hypothesis_tournament: boolean;
            /** Default Source Limit */
            default_source_limit: number;
            id: components["schemas"]["ReasoningPolicyId"];
            /** Max Parallel Tasks */
            max_parallel_tasks: number;
            /** Require Citation Verification */
            require_citation_verification: boolean;
            /** Require Claim Check */
            require_claim_check: boolean;
            /**
             * Require Human Approval For High Risk
             * @constant
             */
            require_human_approval_for_high_risk: true;
            /** Timeout Seconds */
            timeout_seconds: number;
        };
        /**
         * ReasoningPolicyId
         * @enum {string}
         */
        ReasoningPolicyId: "quick" | "standard" | "rigorous";
        /**
         * ResearchRun
         * @description One agent work order with budget, lifecycle state and Temporal linkage.
         */
        ResearchRun: {
            budget: components["schemas"]["Budget"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Created By */
            created_by: string;
            /** Id */
            id: string;
            /** Input Artifact Ids */
            input_artifact_ids?: string[];
            /** Output Artifact Ids */
            output_artifact_ids?: string[];
            /**
             * Parent Run Id
             * @default null
             */
            parent_run_id: string | null;
            /** Project Id */
            project_id: string;
            /** Reasoning Policy Id */
            reasoning_policy_id: string;
            run_type: components["schemas"]["RunType"];
            spent?: components["schemas"]["Spent"];
            status: components["schemas"]["RunStatus"];
            /**
             * Temporal Run Id
             * @default null
             */
            temporal_run_id: string | null;
            /**
             * Temporal Workflow Id
             * @default null
             */
            temporal_workflow_id: string | null;
            /** Tenant Id */
            tenant_id: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Version
             * @default 0
             */
            version: number;
        };
        /**
         * RetentionPolicy
         * @enum {string}
         */
        RetentionPolicy: "project" | "temporary" | "legal_hold";
        /**
         * RightsStatus
         * @enum {string}
         */
        RightsStatus: "open" | "licensed" | "user_provided" | "metadata_only" | "restricted" | "unknown";
        /**
         * RiskTier
         * @enum {string}
         */
        RiskTier: "low" | "moderate" | "high" | "prohibited";
        /**
         * RunCreationAccepted
         * @description 202 response body of ``POST /api/research/v1/runs``.
         */
        RunCreationAccepted: {
            /** Events Url */
            events_url: string;
            /** Run Id */
            run_id: string;
            /**
             * Status
             * @default queued
             * @constant
             */
            status: "queued";
        };
        /**
         * RunEvent
         * @description Append-only run event; ``sequence`` is strictly increasing per run and
         *     drives the SSE Last-Event-ID resume protocol.
         */
        RunEvent: {
            /** Actor Id */
            actor_id: string;
            actor_type: components["schemas"]["ActorType"];
            /** Artifact Ids */
            artifact_ids?: string[];
            /** @default null */
            error: components["schemas"]["RunEventError"] | null;
            /** Event Id */
            event_id: string;
            event_type: components["schemas"]["RunEventType"];
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Payload */
            payload?: {
                [key: string]: unknown;
            };
            progress?: components["schemas"]["RunEventProgress"];
            /** Run Id */
            run_id: string;
            /** Sequence */
            sequence: number;
            /**
             * Step Id
             * @default null
             */
            step_id: string | null;
            /** Trace Id */
            trace_id: string;
        };
        /** RunEventError */
        RunEventError: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Retryable */
            retryable: boolean;
        };
        /** RunEventProgress */
        RunEventProgress: {
            /**
             * Current
             * @default null
             */
            current: number | null;
            /**
             * Message
             * @default null
             */
            message: string | null;
            /**
             * Total
             * @default null
             */
            total: number | null;
            /**
             * Unit
             * @default null
             */
            unit: string | null;
        };
        /**
         * RunEventType
         * @enum {string}
         */
        RunEventType: "run.created" | "run.started" | "step.started" | "step.progress" | "artifact.created" | "evidence.linked" | "approval.requested" | "approval.resolved" | "step.failed" | "run.paused" | "run.resumed" | "run.completed" | "run.failed" | "run.cancelled";
        /**
         * RunStatus
         * @enum {string}
         */
        RunStatus: "queued" | "running" | "waiting_for_approval" | "paused" | "succeeded" | "failed" | "cancelled";
        /**
         * RunType
         * @enum {string}
         */
        RunType: "literature_search" | "document_parse" | "translation" | "writing" | "review" | "math_verification" | "research_cycle";
        /**
         * Sensitivity
         * @enum {string}
         */
        Sensitivity: "public" | "project" | "private" | "restricted";
        /** SourceIdentifier */
        SourceIdentifier: {
            scheme: components["schemas"]["SourceScheme"];
            /** Value */
            value: string;
        };
        /**
         * SourceScheme
         * @enum {string}
         */
        SourceScheme: "doi" | "arxiv" | "pmid" | "openalex" | "datacite" | "internal";
        /** Spent */
        Spent: {
            /**
             * Cost Minor Units
             * @default 0
             */
            cost_minor_units: number;
            /**
             * Model Tokens
             * @default 0
             */
            model_tokens: number;
            /**
             * Runtime Seconds
             * @default 0
             */
            runtime_seconds: number;
            /**
             * Tool Calls
             * @default 0
             */
            tool_calls: number;
        };
        /**
         * SupportStatus
         * @enum {string}
         */
        SupportStatus: "supported" | "partially_supported" | "contradicted" | "insufficient_evidence" | "inference" | "not_verified";
        /**
         * ToolCall
         * @description One invocation of a tool inside a run.
         *
         *     M0 addition over 02 §5.14: ``tenant_id``/``project_id`` explicit.
         */
        ToolCall: {
            /**
             * Approval Request Id
             * @default null
             */
            approval_request_id: string | null;
            /** Arguments Hash */
            arguments_hash: string;
            /**
             * Ended At
             * @default null
             */
            ended_at: string | null;
            /** Id */
            id: string;
            /** Output Artifact Ids */
            output_artifact_ids?: string[];
            /** Project Id */
            project_id: string;
            /** Run Id */
            run_id: string;
            /**
             * Started At
             * @default null
             */
            started_at: string | null;
            status: components["schemas"]["ToolCallStatus"];
            /** Tenant Id */
            tenant_id: string;
            /** Tool Id */
            tool_id: string;
            /** Tool Version */
            tool_version: string;
            /** Trace Id */
            trace_id: string;
        };
        /**
         * ToolCallStatus
         * @enum {string}
         */
        ToolCallStatus: "proposed" | "approved" | "running" | "succeeded" | "failed" | "rejected" | "timed_out";
        /**
         * ToolDefinition
         * @description Static tool descriptor advertised by modules (not tenant-scoped).
         */
        ToolDefinition: {
            adapter_type: components["schemas"]["AdapterType"];
            idempotency: components["schemas"]["IdempotencyKind"];
            /** Input Schema */
            input_schema: {
                [key: string]: unknown;
            };
            network_policy: components["schemas"]["NetworkPolicy"];
            /** Output Schema */
            output_schema: {
                [key: string]: unknown;
            };
            /** Required Permissions */
            required_permissions?: string[];
            risk_tier: components["schemas"]["RiskTier"];
            /** Timeout Seconds */
            timeout_seconds: number;
            /** Tool Id */
            tool_id: string;
            /** Version */
            version: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * VerificationMethod
         * @enum {string}
         */
        VerificationMethod: "syntax" | "assumption" | "unit" | "symbolic" | "numeric" | "counterexample" | "lean_translation" | "lean_kernel" | "citation_metadata" | "citation_entailment" | "formula_fidelity" | "latex_compile" | "human_review";
        /**
         * VerificationRecord
         * @description M0 addition over 02 §5.6: ``tenant_id``/``project_id`` made explicit per
         *     the 02 §4 rule that all tenant data carries tenant_id.
         */
        VerificationRecord: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Created By Activity Id */
            created_by_activity_id: string;
            /** Environment Digest */
            environment_digest: string;
            /** Id */
            id: string;
            /** Input Hashes */
            input_hashes?: string[];
            /** Limitations */
            limitations?: string[];
            method: components["schemas"]["VerificationMethod"];
            /** Project Id */
            project_id: string;
            /**
             * Raw Artifact Id
             * @default null
             */
            raw_artifact_id: string | null;
            status: components["schemas"]["VerificationStatus"];
            /** Summary */
            summary: string;
            /** Target Id */
            target_id: string;
            target_type: components["schemas"]["VerificationTargetType"];
            /** Tenant Id */
            tenant_id: string;
            /** Tool Name */
            tool_name: string;
            /** Tool Version */
            tool_version: string;
        };
        /**
         * VerificationStatus
         * @enum {string}
         */
        VerificationStatus: "passed" | "failed" | "partial" | "inconclusive" | "not_applicable" | "not_run";
        /**
         * VerificationTargetType
         * @enum {string}
         */
        VerificationTargetType: "claim" | "formula" | "citation" | "translation" | "latex_build" | "artifact" | "hypothesis";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create_run_api_research_v1_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRunRequest"];
            };
        };
        responses: {
            /** @description Run accepted; consume events at events_url (SSE). */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunCreationAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_run_events_api_research_v1_runs__run_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server-sent stream of RunEvents; resume with Last-Event-ID. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "text/event-stream": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    liveness_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    readiness_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
