/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 发现当前服务能力与推荐模式 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 能力快照 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CapabilityEnvelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询运行记录 */
        get: {
            parameters: {
                query?: {
                    cursor?: components["parameters"]["Cursor"];
                    limit?: components["parameters"]["Limit"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["Success"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取运行快照 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    run_id: components["parameters"]["RunId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 运行快照 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RunEnvelope"];
                    };
                };
                404: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 订阅运行事件 */
        get: {
            parameters: {
                query?: never;
                header?: {
                    "Last-Event-ID"?: string;
                };
                path: {
                    run_id: components["parameters"]["RunId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description SSE 事件流 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 取消运行 */
        post: {
            parameters: {
                query?: never;
                header: {
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path: {
                    run_id: components["parameters"]["RunId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["Success"];
                409: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 以新 run 重试 */
        post: {
            parameters: {
                query?: never;
                header: {
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path: {
                    run_id: components["parameters"]["RunId"];
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        requested_mode?: components["schemas"]["RequestedMode"];
                        reason?: string;
                    };
                };
            };
            responses: {
                /** @description 新运行 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RunEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 项目列表 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["Success"];
            };
        };
        put?: never;
        /** 创建研究项目 */
        post: {
            parameters: {
                query?: never;
                header: {
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ProjectCreate"];
                };
            };
            responses: {
                201: components["responses"]["Success"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 项目详情 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    project_id: components["parameters"]["ProjectId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["Success"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 更新项目 */
        patch: {
            parameters: {
                query?: never;
                header: {
                    "If-Match": string;
                };
                path: {
                    project_id: components["parameters"]["ProjectId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["Success"];
                409: components["responses"]["Error"];
            };
        };
        trace?: never;
    };
    "/projects/{project_id}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 追加证据 */
        post: {
            parameters: {
                query?: never;
                header: {
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path: {
                    project_id: components["parameters"]["ProjectId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["EvidenceCreate"];
                };
            };
            responses: {
                201: components["responses"]["Success"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/literature/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 多源或本地文献检索 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LiteratureSearch"];
                };
            };
            responses: {
                200: components["responses"]["Success"];
                503: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/verifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 创建数学验证运行 */
        post: {
            parameters: {
                query?: never;
                header: {
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["VerificationCreate"];
                };
            };
            responses: {
                /** @description 验证运行 */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RunEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/verifications/{verification_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 验证详情与五能力结果 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    verification_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["Success"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/formal/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 创建 Lean4 形式化项目 */
        post: {
            parameters: {
                query?: never;
                header: {
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                201: components["responses"]["Success"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/formal/projects/{formal_project_id}/build": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 在后端构建 Lean4 目标 */
        post: {
            parameters: {
                query?: never;
                header: {
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path: {
                    formal_project_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LeanBuild"];
                };
            };
            responses: {
                /** @description Lean 构建运行 */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RunEnvelope"];
                    };
                };
                422: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/manuscripts/{manuscript_id}/compile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Tectonic 后端编译 */
        post: {
            parameters: {
                query?: never;
                header: {
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path: {
                    manuscript_id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        root_file: string;
                        /** @constant */
                        engine?: "tectonic";
                        /** @default true */
                        synctex?: boolean;
                        requested_mode?: components["schemas"]["RequestedMode"];
                    };
                };
            };
            responses: {
                /** @description 编译运行 */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RunEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/review-batches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 创建论文初审批次 */
        post: {
            parameters: {
                query?: never;
                header: {
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ReviewBatchCreate"];
                };
            };
            responses: {
                201: components["responses"]["Success"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/education/datasets/preflight": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 教育数据隐私预检 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["EducationQuery"];
                };
            };
            responses: {
                200: components["responses"]["Success"];
                422: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/education/datasets/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 创建匿名数据快照 */
        post: {
            parameters: {
                query?: never;
                header: {
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["EducationQuery"];
                };
            };
            responses: {
                /** @description 数据快照运行 */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RunEnvelope"];
                    };
                };
                422: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/publications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 跨端发布带血缘的副本 */
        post: {
            parameters: {
                query?: never;
                header: {
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PublicationCreate"];
                };
            };
            responses: {
                201: components["responses"]["Success"];
                403: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @default auto
         * @enum {string}
         */
        RequestedMode: "auto" | "full" | "local_engine" | "browser_local";
        /** @enum {string} */
        ResolvedMode: "full" | "local_engine" | "browser_local" | "unavailable";
        /** @enum {string} */
        RunStatus: "queued" | "preparing" | "running" | "awaiting_confirm" | "cancelling" | "succeeded" | "failed" | "timed_out" | "out_of_memory" | "cancelled" | "infra_error";
        Meta: {
            request_id: string;
            trace_id: string;
            /** Format: date-time */
            server_time: string;
        };
        SuccessEnvelope: {
            /** @constant */
            success: true;
            data: unknown;
            meta: components["schemas"]["Meta"];
        };
        ErrorEnvelope: {
            /** @constant */
            success: false;
            error: {
                code: string;
                message: string;
                retryable: boolean;
                details?: Record<string, never>;
            };
            meta: components["schemas"]["Meta"];
        };
        ModeEvidence: {
            resolved_mode: components["schemas"]["ResolvedMode"];
            capabilities_used: string[];
            missing_capabilities: string[];
            degraded_reasons?: {
                capability?: string;
                reason?: string;
            }[];
        };
        Run: components["schemas"]["ModeEvidence"] & {
            run_id: string;
            project_id?: string | null;
            kind: string;
            status: components["schemas"]["RunStatus"];
            phase?: string | null;
            progress?: number;
            requested_mode?: components["schemas"]["RequestedMode"];
            input_hash: string;
            parent_run_id?: string | null;
            executor?: {
                name?: string;
                version?: string;
                image_digest?: string | null;
            };
            trace_id: string;
        };
        RunEnvelope: {
            /** @constant */
            success: true;
            data: components["schemas"]["Run"];
            meta: components["schemas"]["Meta"];
        };
        CapabilityEnvelope: {
            /** @constant */
            success: true;
            data: {
                recommended_mode: components["schemas"]["ResolvedMode"];
                capabilities: {
                    key: string;
                    available: boolean;
                    provider?: string;
                    version?: string | null;
                    health: string;
                }[];
            };
            meta: components["schemas"]["Meta"];
        };
        ProjectCreate: {
            title: string;
            research_question: string;
            domain: string;
            /** @enum {string} */
            stage?: "discovery" | "verification" | "writing" | "review" | "published";
            /** @enum {string} */
            visibility?: "private" | "team";
        };
        EvidenceCreate: {
            type: string;
            title: string;
            source: Record<string, never>;
            locator?: Record<string, never>;
            run_id?: string | null;
            input_hash?: string | null;
            /** @enum {string} */
            trust_level: "source_observation" | "rule_checked" | "numeric_sampled" | "symbolic_verified" | "deterministic_verified" | "ai_suggestion" | "user_asserted";
        };
        LiteratureSearch: {
            project_id?: string | null;
            query: string;
            filters?: Record<string, never>;
            sources?: ("crossref" | "openalex" | "semantic_scholar" | "local")[];
            requested_mode?: components["schemas"]["RequestedMode"];
            limit?: number;
        };
        VerificationCreate: {
            project_id?: string;
            source?: Record<string, never>;
            expression: string;
            /** @enum {string} */
            format: "latex" | "plain" | "json";
            variables: Record<string, never>[];
            assumptions?: string[];
            units?: Record<string, never>;
            capabilities: ("numeric" | "symbolic" | "dimensions" | "inequality" | "counterexample")[];
            requested_mode?: components["schemas"]["RequestedMode"];
        };
        LeanBuild: {
            target: string;
            /** @default true */
            no_sorry: boolean;
            requested_mode?: components["schemas"]["RequestedMode"];
            return_context?: Record<string, never>;
        };
        ReviewBatchCreate: {
            project_id: string;
            title: string;
            /** @enum {string} */
            mode: "author" | "reviewer";
            rule_set: string;
            checks: string[];
        };
        EducationQuery: {
            product_id: string;
            scope: Record<string, never>;
            dimensions: string[];
            metrics: string[];
        };
        PublicationCreate: {
            source: Record<string, never>;
            target: Record<string, never>;
            /** @enum {string} */
            policy: "copy_with_lineage" | "reference_only";
            message?: string;
        };
    };
    responses: {
        /** @description 成功信封 */
        Success: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["SuccessEnvelope"];
            };
        };
        /** @description 错误信封 */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        RunId: string;
        ProjectId: string;
        Cursor: string;
        Limit: number;
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
