<template><main class="admin-page"><AdminNav/><header><div><span class="tag">管理员</span><h1>身份审核中心</h1><p>审核教师与科研人员申请，所有决定都会写入审计日志。</p></div><button class="btn" @click="load">刷新队列</button></header><div class="filters"><select v-model="filter" class="select" aria-label="申请状态"><option value="pending">待审核</option><option value="needs_more_info">待补材料</option><option value="approved">已通过</option><option value="rejected">未通过</option><option value="">全部</option></select><input v-model="reauthProof" class="input" aria-label="近期重新认证凭据" placeholder="敏感操作前请完成近期重新认证" /></div><p v-if="error" class="error">{{error}}</p><section class="queue"><article v-for="item in visible" :key="item.id"><div class="summary"><div><strong>{{roleName[item.role]||item.role}}</strong><span :class="['tag',item.status]">{{statusName[item.status]||item.status}}</span></div><h2>{{item.organization_name||'未填写机构'}}</h2><p>申请编号：{{item.id}}</p></div><textarea v-model="notes[item.id]" class="textarea" placeholder="审核意见（驳回或补材料时必填）"></textarea><div class="actions"><button class="btn" @click="review(item,'more')">要求补充</button><button class="btn btn-danger" @click="review(item,'reject')">驳回</button><button class="btn btn-primary" data-action="approve" @click="review(item,'approve')">批准</button></div></article><p v-if="!visible.length" class="empty">当前筛选下没有申请</p></section></main></template>
<script setup>
import { computed,onMounted,reactive,ref } from 'vue';import { adminIdentityApi } from '@/api/auth';import AdminNav from '@/components/admin/AdminNav.vue'
const props=defineProps({initialApplications:{type:Array,default:()=>[]},initialReauthProof:{type:String,default:''}});const applications=ref([...props.initialApplications]),filter=ref('pending'),reauthProof=ref(props.initialReauthProof),notes=reactive({}),error=ref('');const roleName={teacher:'教师',researcher:'科研人员'},statusName={pending:'待审核',needs_more_info:'待补材料',approved:'已通过',rejected:'未通过'};const visible=computed(()=>filter.value?applications.value.filter(x=>x.status===filter.value):applications.value)
async function load(){try{applications.value=await adminIdentityApi.applications(filter.value?{status:filter.value}:{})}catch(e){error.value=e?.message||'加载失败'}}
async function review(item,decision){if(!reauthProof.value){error.value='请先完成近期重新认证';return}error.value='';const note=notes[item.id]||'';try{const data=decision==='approve'?await adminIdentityApi.approve(item.id,note,reauthProof.value):decision==='reject'?await adminIdentityApi.reject(item.id,note,reauthProof.value):await adminIdentityApi.requestMoreInfo(item.id,note,reauthProof.value);item.status=data.status}catch(e){error.value=e?.message||'审核失败'}}
onMounted(()=>{if(!applications.value.length)load()})
</script>
<style scoped>.admin-page{min-height:100vh;background:var(--bg);padding:28px max(4vw,24px)}header{display:flex;justify-content:space-between;align-items:end;margin:28px 0 18px}header p,.summary p{color:var(--ink2)}h1{margin:10px 0 3px}.filters{display:grid;grid-template-columns:220px 1fr;gap:12px}.queue{display:grid;gap:14px;margin-top:18px}.queue article{background:white;border:1px solid var(--line);border-radius:16px;padding:20px;display:grid;grid-template-columns:minmax(220px,1fr) minmax(240px,1fr);gap:16px}.summary>div{display:flex;align-items:center;gap:10px}.summary h2{font-size:17px;margin:8px 0 2px}.actions{grid-column:1/-1;display:flex;justify-content:flex-end;gap:8px}.error{margin-top:12px;padding:10px;background:var(--err-bg);color:var(--err-deep);border-radius:10px}.empty{padding:36px;text-align:center;color:var(--ink3)}@media(max-width:700px){.filters,.queue article{grid-template-columns:1fr}}</style>
